site_name: RAW App Documentation

nav:
  - Home: index.md
  - API Reference: api.md

theme:
  name: material

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            show_if_no_docstring: true
          paths:
            - "/Users/stevensongerardeustache/Library/Mobile Documents/com~apple~CloudDocs/Desktop/Tech and Faith/GitHub/RAW-APP/backend"
  